
import type { Player } from '@/lib/types';

export const players: Player[] = [
  {
    id: 'p1',
    firstName: 'Alex',
    lastName: 'Johnson',
    birthMonth: 5,
    birthYear: 2002,
    number: 23,
    position: 'Forward',
    avatarId: 'player1',
    teamId: 'team-1',
    contact: { email: 'alex.j@example.com', phone: '555-0101' },
    emergencyContact: { name: 'Sarah Johnson', phone: '555-0201', relation: 'Mother', email: 'sarah.j@example.com' },
    medicalInfo: { allergies: 'None', conditions: 'None' },
    skillAssessments: { shooting: 8, dribbling: 7, passing: 6, defense: 9 }
  },
  {
    id: 'p2',
    firstName: 'Maria',
    lastName: 'Garcia',
    birthMonth: 8,
    birthYear: 2001,
    number: 10,
    position: 'Guard',
    avatarId: 'player2',
    teamId: 'team-1',
    contact: { email: 'maria.g@example.com', phone: '555-0102' },
    emergencyContact: { name: 'Carlos Garcia', phone: '555-0202', relation: 'Father', email: 'carlos.g@example.com' },
    medicalInfo: { allergies: 'Peanuts', conditions: 'Asthma' },
    skillAssessments: { shooting: 9, dribbling: 9, passing: 8, defense: 7 }
  },
    {
    id: 'p3',
    firstName: 'James',
    lastName: 'Smith',
    birthMonth: 11,
    birthYear: 2000,
    number: 34,
    position: 'Center',
    avatarId: 'player3',
    teamId: 'team-1',
    contact: { email: 'james.s@example.com', phone: '555-0103' },
    emergencyContact: { name: 'Emily Smith', phone: '555-0203', relation: 'Wife', email: 'emily.s@example.com' },
    medicalInfo: { allergies: 'None', conditions: 'None' },
    skillAssessments: { shooting: 6, dribbling: 5, passing: 7, defense: 9 }
  },
  {
    id: 'p4',
    firstName: 'Chen',
    lastName: 'Wang',
    birthMonth: 2,
    birthYear: 2003,
    number: 8,
    position: 'Guard',
    avatarId: 'player4',
    teamId: 'team-1',
    contact: { email: 'chen.w@example.com', phone: '555-0104' },
    emergencyContact: { name: 'Li Wang', phone: '555-0204', relation: 'Father', email: 'li.w@example.com' },
    medicalInfo: { allergies: 'None', conditions: 'None' },
    skillAssessments: { shooting: 8, dribbling: 9, passing: 9, defense: 6 }
  },
  {
    id: 'p5',
    firstName: 'Emily',
    lastName: 'Davis',
    birthMonth: 9,
    birthYear: 2002,
    number: 15,
    position: 'Forward',
    avatarId: 'player5',
    teamId: 'team-2',
    contact: { email: 'emily.d@example.com', phone: '555-0105' },
    emergencyContact: { name: 'Robert Davis', phone: '555-0205', relation: 'Father', email: 'robert.d@example.com' },
    medicalInfo: { allergies: 'None', conditions: 'None' },
    skillAssessments: { shooting: 7, dribbling: 7, passing: 8, defense: 8 }
  },
  {
    id: 'p6',
    firstName: 'David',
    lastName: 'Wilson',
    birthMonth: 7,
    birthYear: 2001,
    number: 5,
    position: 'Guard',
    avatarId: 'player6',
    teamId: 'team-2',
    contact: { email: 'david.w@example.com', phone: '555-0106' },
    emergencyContact: { name: 'Jessica Wilson', phone: '555-0206', relation: 'Mother', email: 'jessica.w@example.com' },
    medicalInfo: { allergies: 'Pollen', conditions: 'None' },
    skillAssessments: { shooting: 9, dribbling: 8, passing: 7, defense: 7 }
  },
  {
    id: 'p7',
    firstName: 'Olivia',
    lastName: 'Brown',
    birthMonth: 1,
    birthYear: 2000,
    number: 42,
    position: 'Center',
    avatarId: 'player7',
    teamId: 'team-2',
    contact: { email: 'olivia.b@example.com', phone: '555-0107' },
    emergencyContact: { name: 'Michael Brown', phone: '555-0207', relation: 'Father', email: 'michael.b@example.com' },
    medicalInfo: { allergies: 'None', conditions: 'None' },
    skillAssessments: { shooting: 7, dribbling: 6, passing: 6, defense: 9 }
  },
  {
    id: 'p8',
    firstName: 'Liam',
    lastName: 'Miller',
    birthMonth: 4,
    birthYear: 2003,
    number: 1,
    position: 'Guard',
    avatarId: 'player8',
    teamId: 'team-2',
    contact: { email: 'liam.m@example.com', phone: '555-0108' },
    emergencyContact: { name: 'Sophia Miller', phone: '555-0208', relation: 'Mother', email: 'sophia.m@example.com' },
    medicalInfo: { allergies: 'None', conditions: 'None' },
    skillAssessments: { shooting: 8, dribbling: 9, passing: 8, defense: 8 }
  },
    {
    id: 'p9',
    firstName: 'Sophia',
    lastName: 'Rodriguez',
    birthMonth: 12,
    birthYear: 2001,
    number: 22,
    position: 'Forward',
    avatarId: 'player9',
    teamId: 'team-3',
    contact: { email: 'sophia.r@example.com', phone: '555-0109' },
    emergencyContact: { name: 'Daniel Rodriguez', phone: '555-0209', relation: 'Father', email: 'daniel.r@example.com' },
    medicalInfo: { allergies: 'None', conditions: 'None' },
    skillAssessments: { shooting: 8, dribbling: 7, passing: 8, defense: 8 }
  },
  {
    id: 'p10',
    firstName: 'Michael',
    lastName: 'Jones',
    birthMonth: 3,
    birthYear: 1999,
    number: 30,
    position: 'Guard',
    avatarId: 'player10',
    teamId: 'team-3',
    contact: { email: 'michael.j@example.com', phone: '555-0110' },
    emergencyContact: { name: 'Linda Jones', phone: '555-0210', relation: 'Mother', email: 'linda.j@example.com' },
    medicalInfo: { allergies: 'None', conditions: 'None' },
    skillAssessments: { shooting: 10, dribbling: 9, passing: 8, defense: 7 }
  },
  {
    id: 'p11',
    firstName: 'Isabella',
    lastName: 'Martinez',
    birthMonth: 6,
    birthYear: 2002,
    number: 11,
    position: 'Forward',
    avatarId: 'player11',
    teamId: 'team-3',
    contact: { email: 'isabella.m@example.com', phone: '555-0111' },
    emergencyContact: { name: 'Jose Martinez', phone: '555-0211', relation: 'Father', email: 'jose.m@example.com' },
    medicalInfo: { allergies: 'Dust', conditions: 'None' },
    skillAssessments: { shooting: 7, dribbling: 8, passing: 7, defense: 8 }
  },
  {
    id: 'p12',
    firstName: 'William',
    lastName: 'Taylor',
    birthMonth: 10,
    birthYear: 2000,
    number: 55,
    position: 'Center',
    avatarId: 'player12',
    teamId: 'team-3',
    contact: { email: 'william.t@example.com', phone: '555-0112' },
    emergencyContact: { name: 'Patricia Taylor', phone: '555-0212', relation: 'Mother', email: 'patricia.t@example.com' },
    medicalInfo: { allergies: 'None', conditions: 'None' },
    skillAssessments: { shooting: 6, dribbling: 5, passing: 6, defense: 10 }
  }
];
